### ISSUE TITLE
星座运势查询报错

### ISSUE THREAD

**Issue by Fahaxikiii** [FYWinds/takker#24]
12-09 17:38:52 [SUCCESS] nonebot | CQHTTP 1975969493 | [message.group.normal]: Message -2038913020 from 3116556127@[群:681688017] "sluck"
12-09 17:38:52 [INFO] nonebot | Event will be handled by <Matcher from starluck, type=message, priority=20, temp=False>
12-09 17:38:52 [INFO] nonebot | Matcher <Matcher from starluck, type=message, priority=20, temp=False> running complete
12-09 17:38:52 [ERROR] nonebot | Running matcher <Matcher from starluck, type=message, priority=20, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\takker\bot.py", line 29, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 256, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\uvicorn\main.py", line 447, in run
    server.run()
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\nonebot\handler.py", line 64, in __call__
    await self.func(
  File "C:\Users\Administrator\Desktop\takker\plugins\starluck.py", line 111, in handle_starluck_receive
    await make_cache(stars, stars_cn)
  File "C:\Users\Administrator\Desktop\takker\plugins\starluck.py", line 223, in make_cache
    resp_body = (await get_data(stars[i]))["204017771"]["day"]
  File "C:\Users\Administrator\Desktop\takker\plugins\starluck.py", line 147, in get_data
    return response.json()
  File "C:\Users\Administrator\Desktop\takker\.venv\lib\site-packages\httpx\_models.py", line 1514, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by FYWinds** [comment]
仔细阅读配置文件，星座运势相关功能需要阿里云的apikey，是第三方付费API
[API购买地址](https://market.aliyun.com/products/57126001/cmapi011529.html)

**Comment by Fahaxikiii** [comment]
> 仔细阅读配置文件，星座运势相关功能需要阿里云的apikey，是第三方付费API
> [API购买地址](https://market.aliyun.com/products/57126001/cmapi011529.html)

是我买错了api,(ο̬̬̬̬̬̬̬̏̃ɷο̬̬̬̬̬̬̬̏̃)
