### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by Fahaxikiii** [FYWinds/takker#28]
root@VM-16-3-ubuntu:/www/wwwroot/takker-1.3.0# poetry run python bot.py
02-27 16:32:57 [INFO] utils | 已禁用uvicorn自动重载
Traceback (most recent call last):
  File "bot.py", line 5, in <module>
    from service.init import init_bot_startup, update_plugin_list
  File "/www/wwwroot/takker-1.3.0/service/init.py", line 5, in <module>
    from service.db.db_connect import db_init
  File "/www/wwwroot/takker-1.3.0/service/db/db_connect.py", line 8, in <module>
    models: list[str] = [
TypeError: 'type' object is not subscriptable
root@VM-16-3-ubuntu:/www/wwwroot/takker-1.3.0#

**Comment by FYWinds** [comment]
请检查python版本是否为python3.9+，小写list作为typing是py3.9后添加的feature

(奇怪，pyproject.toml内应该要求了python版本大于3.9，未达成要求应该虚拟环境都创建不了
