### ISSUE TITLE
无法找到指定的模块

### ISSUE THREAD

**Issue by Nthing734** [FYWinds/takker#31]
07-23 23:21:25 [ERROR] nonebot | Failed to import "bili_sub"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\takker\bot.py", line 22, in <module>
    nonebot.load_plugins("plugins")
  File "C:\Users\Administrator\Desktop\bot\takker\.venv\lib\site-packages\nonebot\plugin\__init__.py", line 997, in loa
_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "C:\Users\Administrator\Desktop\bot\takker\.venv\lib\site-packages\nonebot\plugin\__init__.py", line 945, in _lo
d_plugin
    module = manager.load_plugin(plugin_name)
  File "C:\Users\Administrator\Desktop\bot\takker\.venv\lib\site-packages\nonebot\plugin\manager.py", line 161, in load
plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_m
dule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\bot\takker\.venv\lib\site-packages\nonebot\plugin\manager.py", line 267, in exec
module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\bot\takker\plugins\bili_sub\__init__.py", line 11, in <module>
    from utils.img_util import create_image_from_text
  File "C:\Users\Administrator\Desktop\bot\takker\utils\img_util.py", line 7, in <module>
    import cv2
  File "C:\Users\Administrator\Desktop\bot\takker\.venv\lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

**Comment by FYWinds** [comment]
看上去是缺少 opencv-python 包的缘故，但是缺少这个包大概率还缺少其他运行库，暂时无法判断
请尝试 `pip install opencv-python` 后提供一下其他信息（如系统版本，python版本等）

**Comment by Nthing734** [comment]
> 看上去是缺少 opencv-python 包的缘故，但是缺少这个包大概率还缺少其他运行库，暂时无法判断 请尝试 `pip install opencv-python` 后提供一下其他信息（如系统版本，python版本等）

Windows server 2012R2 Python3.9.13

**Comment by FYWinds** [comment]
> Windows server 2012R2
如果安装opencv-python后还无法使用的话，请尝试更换windows server 2016或windows10及以上

也可以换用 https://github.com/HibiKier/zhenxun_bot 

我目前没有什么精力持续维护此bot
