### ISSUE TITLE
python bot.py报错

### ISSUE THREAD

**Issue by LuciTc** [FYWinds/takker#6]
Traceback (most recent call last):
  File "/root/qbot/takker/bot.py", line 1, in <module>
    import nonebot
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 138, in <module>
    from .command import CommandSession, CommandGroup
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/command/__init__.py", line 927, in <module>
    from nonebot.command.group import CommandGroup
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/command/group.py", line 3, in <module>
    from nonebot.plugin import on_command
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/plugin/__init__.py", line 17, in <module>
    from nonebot.matcher import Matcher
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/matcher.py", line 16, in <module>
    from nonebot.rule import Rule
  File "/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/rule.py", line 21, in <module>
    from nonebot import get_driver
ImportError: cannot import name 'get_driver' from partially initialized module 'nonebot' (most likely due to a circular import) (/root/.cache/pypoetry/virtualenvs/takker-reborn-NcqX0U7w-py3.9/lib/python3.9/site-packages/nonebot/__init__.py)

**Comment by FYWinds** [comment]
是否是使用的poetry install安装依赖，你这nonebot1和2混装了

**Comment by LuciTc** [comment]
因为他报错  我还以为是nonebot安装出问题了，我手动执行了一下 pip3 install nonebot

**Comment by FYWinds** [comment]
那么请在环境中`pip freeze | xargs pip uninstall -y` ，并重新执行`poetry install`

**Comment by LuciTc** [comment]
pip freeze | xargs pip uninstall -y后ERROR: Invalid requirement: '@'

**Comment by LuciTc** [comment]
解决了  pip freeze > 1.txt，执行 pip uninstall -r 1.txt -y解决
